org.gradle.jvmargs=-Xmx2G
minecraft.version=1.8.9
loom.platform=forge
mod.version=1.0.6

group=at.yedel
mod.name=DreamersDeluxe
mod.id=dreamersdeluxe
mod.description=BedWars features to support the dreamers' lifestyle
project.group=at.yedel
project.description=BedWars features to support the dreamers' lifestyle

oneconfigVersion=0.2.2-alpha+
oneconfigWrapperVersion=1.0.0-beta+
modApiVersion=1.0.1.2
devAuthVersion=1.2.2



