org.gradle.jvmargs=-Xmx2G
loomx.loom_version=1.17.4

group=at.yedel
version=2.0.0-beta.1
mod.name=DreamersDeluxe
mod.id=dreamersdeluxe
mod.description=BedWars features to support the dreamers' lifestyle
modIcon=assets/dreamersdeluxe/dreamersdeluxe.png
license=LGPL-3.0-only
modrinthLogoLink=https://cdn.modrinth.com/data/cached_images/aa92b26fd7b3679026b323110a565514dd4bd3cc.png