org.gradle.jvmargs=-Xmx2G

group=at.yedel
version=1.0.7-beta.1
mod.description=BedWars features to support the dreamers' lifestyle
license=LGPL-3.0-only
modrinthLogoLink=https://cdn.modrinth.com/data/cached_images/aa92b26fd7b3679026b323110a565514dd4bd3cc.png

minecraft.version=1.8.9
loom.platform=forge
mod.name=DreamersDeluxe
mod.id=dreamersdeluxe
project.group=at.yedel


